elasticcommonfields: {}
id: crowdstrike_falconhost_test
version: -1
contentitemexportablefields:
  contentitemfields:
    propagationLabels:
    - all
name: CrowdStrike FalconHost Test
starttaskid: "0"
tasks:
  "0":
    id: "0"
    taskid: "15"
    type: start
    task:
      elasticcommonfields: {}
      id: "15"
      version: -1
      name: ""
      iscommand: false
      brand: ""
    nexttasks:
      '#none#':
      - "8"
    separatecontext: false
    view: |-
      {
        "position": {
          "x": 275,
          "y": 50
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
    skipunavailable: false
    quiet: false
  "7":
    id: "7"
    taskid: "24"
    type: regular
    task:
      elasticcommonfields: {}
      id: "24"
      version: -1
      name: Search devices
      description: Search for devices in your environment by platform, host name,
        IP, or a number of other parameters
      script: FalconHost|||cs-device-search
      type: regular
      iscommand: true
      brand: FalconHost
    nexttasks:
      '#none#':
      - "13"
    scriptarguments:
      filter: {}
      limit: {}
      offset:
        simple: "1"
      query: {}
    separatecontext: false
    view: |-
      {
        "position": {
          "x": 275,
          "y": 370
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
    skipunavailable: false
    quiet: false
  "8":
    id: "8"
    taskid: "16"
    type: regular
    task:
      elasticcommonfields: {}
      id: "16"
      version: -1
      name: DeleteContext
      description: Delete field from context
      scriptName: DeleteContext
      type: regular
      iscommand: false
      brand: ""
    nexttasks:
      '#none#':
      - "7"
    scriptarguments:
      all:
        simple: "yes"
      key: {}
    separatecontext: false
    view: |-
      {
        "position": {
          "x": 275,
          "y": 195
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
    skipunavailable: false
    quiet: false
  "13":
    id: "13"
    taskid: "20"
    type: condition
    task:
      elasticcommonfields: {}
      id: "20"
      version: -1
      name: Found any devices?
      type: condition
      iscommand: false
      brand: ""
    nexttasks:
      '#default#':
      - "31"
      "yes":
      - "15"
    separatecontext: false
    conditions:
    - label: "yes"
      condition:
      - - operator: isExists
          left:
            value:
              complex:
                root: FalconHostDevices
            iscontext: true
    view: |-
      {
        "position": {
          "x": 275,
          "y": 545
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
    skipunavailable: false
    quiet: false
  "15":
    id: "15"
    taskid: "21"
    type: regular
    task:
      elasticcommonfields: {}
      id: "21"
      version: -1
      name: Get device details
      description: Get details for one or more devices, according to device ID
      script: FalconHost|||cs-device-details
      type: regular
      iscommand: true
      brand: FalconHost
    nexttasks:
      '#none#':
      - "16"
    scriptarguments:
      ids:
        simple: ${FalconHostDevices}
    separatecontext: false
    view: |-
      {
        "position": {
          "x": 162.5,
          "y": 720
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
    skipunavailable: false
    quiet: false
  "16":
    id: "16"
    taskid: "17"
    type: regular
    task:
      elasticcommonfields: {}
      id: "17"
      version: -1
      name: Verify Endpoint
      description: |-
        Verifies path in context:
        - Verifies path existence
        - If matching object is an array: verify fields exists in each of the objects in the array
        - If matching object is not an array: verify fields exists in matching object
        - if 'expectedValue' is given: ensure that the given value is equal to the context path
      scriptName: VerifyContext
      type: regular
      iscommand: false
      brand: ""
    nexttasks:
      '#none#':
      - "19"
    scriptarguments:
      expectedValue: {}
      fields: {}
      path:
        simple: Endpoint
    separatecontext: false
    view: |-
      {
        "position": {
          "x": 162.5,
          "y": 895
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
    skipunavailable: false
    quiet: false
  "17":
    id: "17"
    taskid: "22"
    type: regular
    task:
      elasticcommonfields: {}
      id: "22"
      version: -1
      name: Search by MD5
      description: Returns a list of device IDs on which an indicator ran
      script: FalconHost|||cs-device-ran-on
      type: regular
      iscommand: true
      brand: FalconHost
    nexttasks:
      '#none#':
      - "24"
    scriptarguments:
      type:
        simple: md5
      value:
        simple: 36bd4be7042f6de7e332c05cef287d05
    separatecontext: false
    view: |-
      {
        "position": {
          "x": 162.5,
          "y": 1245
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
    skipunavailable: false
    quiet: false
  "18":
    id: "18"
    taskid: "18"
    type: regular
    task:
      elasticcommonfields: {}
      id: "18"
      version: -1
      name: Get details
      description: Get details for one or more devices, according to device ID
      script: FalconHost|||cs-device-details
      type: regular
      iscommand: true
      brand: FalconHost
    nexttasks:
      '#none#':
      - "23"
    scriptarguments:
      ids:
        simple: ${FalconHostDevices}
    separatecontext: false
    view: |-
      {
        "position": {
          "x": 50,
          "y": 1595
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
    skipunavailable: false
    quiet: false
  "19":
    id: "19"
    taskid: "25"
    type: regular
    task:
      elasticcommonfields: {}
      id: "25"
      version: -1
      name: Delete Context
      description: Delete field from context
      scriptName: DeleteContext
      type: regular
      iscommand: false
      brand: ""
    nexttasks:
      '#none#':
      - "17"
    scriptarguments:
      all:
        simple: "yes"
      index: {}
      key: {}
      keysToKeep: {}
      subplaybook: {}
    separatecontext: false
    view: |-
      {
        "position": {
          "x": 162.5,
          "y": 1070
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
    skipunavailable: false
    quiet: false
  "21":
    id: "21"
    taskid: "19"
    type: regular
    task:
      elasticcommonfields: {}
      id: "19"
      version: -1
      name: Search with number offset
      description: Search for devices in your environment by platform, host name,
        IP, or various other parameters
      script: FalconHost|||cs-device-search
      type: regular
      iscommand: true
      brand: FalconHost
    nexttasks:
      '#none#':
      - "22"
    scriptarguments:
      filter: {}
      limit: {}
      offset:
        simple: ${Offset}
      query: {}
    separatecontext: false
    view: |-
      {
        "position": {
          "x": 162.5,
          "y": 1945
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
    skipunavailable: false
    quiet: false
  "22":
    id: "22"
    taskid: "26"
    type: regular
    task:
      elasticcommonfields: {}
      id: "26"
      version: -1
      name: Get device details
      description: Get details for one or more devices, according to device ID
      script: FalconHost|||cs-device-details
      type: regular
      iscommand: true
      brand: FalconHost
    nexttasks:
      '#none#':
      - "31"
    scriptarguments:
      ids:
        simple: ${FalconHostDevices}
    separatecontext: false
    view: |-
      {
        "position": {
          "x": 162.5,
          "y": 2120
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
    skipunavailable: false
    quiet: false
  "23":
    id: "23"
    taskid: "27"
    type: regular
    task:
      elasticcommonfields: {}
      id: "27"
      version: -1
      name: Set number offset
      description: Sets a value into the context with the given context key
      scriptName: Set
      type: regular
      iscommand: false
      brand: ""
    nexttasks:
      '#none#':
      - "21"
    scriptarguments:
      append: {}
      key:
        simple: Offset
      value:
        simple: "1"
    separatecontext: false
    view: |-
      {
        "position": {
          "x": 162.5,
          "y": 1770
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
    skipunavailable: false
    quiet: false
  "24":
    id: "24"
    taskid: "23"
    type: condition
    task:
      elasticcommonfields: {}
      id: "23"
      version: -1
      name: Found any devices?
      type: condition
      iscommand: false
      brand: ""
    nexttasks:
      '#default#':
      - "23"
      "yes":
      - "18"
    separatecontext: false
    conditions:
    - label: "yes"
      condition:
      - - operator: isExists
          left:
            value:
              complex:
                root: FalconHostDevices
            iscontext: true
    view: |-
      {
        "position": {
          "x": 162.5,
          "y": 1420
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
    skipunavailable: false
    quiet: false
  "25":
    id: "25"
    taskid: "163"
    type: condition
    task:
      elasticcommonfields: {}
      id: "163"
      version: -1
      name: Check detections were fetched
      description: Check detections were fetched
      type: condition
      iscommand: false
      brand: ""
    nexttasks:
      '#default#':
      - "27"
      "yes":
      - "26"
    separatecontext: false
    conditions:
    - label: "yes"
      condition:
      - - operator: isExists
          left:
            value:
              complex:
                root: CrowdStrikeHost
                accessor: Detections.detection_id
            iscontext: true
      - - operator: greaterThan
          left:
            value:
              complex:
                root: CrowdStrikeHost
                accessor: Detections.detection_id
                transformers:
                - operator: count
            iscontext: true
          right:
            value:
              simple: "1"
    view: |-
      {
        "position": {
          "x": 275,
          "y": 2500
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
    skipunavailable: false
    quiet: false
  "26":
    id: "26"
    taskid: "164"
    type: regular
    task:
      elasticcommonfields: {}
      id: "164"
      version: -1
      name: Get Detection Details
      description: Fetch details of a Crowdstrike Detection using the detection ID
      script: '|||cs-detection-details'
      type: regular
      iscommand: true
      brand: ""
    nexttasks:
      '#none#':
      - "28"
    scriptarguments:
      detection_id:
        complex:
          root: CrowdStrikeHost
          accessor: Detections.detection_id
    separatecontext: false
    view: |-
      {
        "position": {
          "x": 60,
          "y": 2755
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
    skipunavailable: false
    quiet: false
  "27":
    id: "27"
    taskid: "165"
    type: title
    task:
      elasticcommonfields: {}
      id: "165"
      version: -1
      name: No Detections to check
      type: title
      iscommand: false
      brand: ""
    separatecontext: false
    view: |-
      {
        "position": {
          "x": 542.5,
          "y": 2755
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
    skipunavailable: false
    quiet: false
  "28":
    id: "28"
    taskid: "166"
    type: condition
    task:
      elasticcommonfields: {}
      id: "166"
      version: -1
      name: Assert detections details were fetched
      description: Assert detections details were fetched
      type: condition
      iscommand: false
      brand: ""
    nexttasks:
      "yes":
      - "29"
    separatecontext: false
    conditions:
    - label: "yes"
      condition:
      - - operator: isExists
          left:
            value:
              complex:
                root: CrowdStrikeHost
                accessor: Detections.first_behavior
            iscontext: true
    view: |-
      {
        "position": {
          "x": 60,
          "y": 2940
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
    skipunavailable: false
    quiet: false
  "29":
    id: "29"
    taskid: "168"
    type: regular
    task:
      elasticcommonfields: {}
      id: "168"
      version: -1
      name: Change Detection to in_progress
      description: Sets the state of a detection in Falcon Host. You can obtain detection
        IDs from the Falcon Host UI or from the Falcon Streaming API.
      script: '|||cs-resolve-detection'
      type: regular
      iscommand: true
      brand: ""
    nexttasks:
      '#none#':
      - "30"
    scriptarguments:
      ids:
        complex:
          root: CrowdStrikeHost
          accessor: Detections.detection_id
      status:
        simple: in_progress
    separatecontext: false
    view: |-
      {
        "position": {
          "x": 60,
          "y": 3120
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
    skipunavailable: false
    quiet: false
  "30":
    id: "30"
    taskid: "160"
    type: title
    task:
      elasticcommonfields: {}
      id: "160"
      version: -1
      name: Done
      description: Done
      type: title
      iscommand: false
      brand: ""
    separatecontext: false
    view: |-
      {
        "position": {
          "x": 60,
          "y": 3320
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
    skipunavailable: false
    quiet: false
  "31":
    id: "31"
    taskid: "161"
    type: regular
    task:
      elasticcommonfields: {}
      id: "161"
      version: -1
      name: Search Detections Since 2017
      description: String search through all Crowdstrike Detection fields.  For example,
        provide a sensor ID to search for all detections that contain that sensor
        ID (and any other fields that would happen to contain it)
      script: '|||cs-detection-search'
      type: regular
      iscommand: true
      brand: ""
    nexttasks:
      '#none#':
      - "25"
    scriptarguments:
      first_behavior:
        simple: "2017-01-31T22:36:11Z"
      query: {}
    separatecontext: false
    view: |-
      {
        "position": {
          "x": 275,
          "y": 2300
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
    skipunavailable: false
    quiet: false
view: |-
  {
    "linkLabelsPosition": {},
    "paper": {
      "dimensions": {
        "height": 3335,
        "width": 872.5,
        "x": 50,
        "y": 50
      }
    }
  }
inputs: []
outputs: []
