id: Office365_Feed_Test
version: -1
contentitemfields:
  propagationLabels: []
name: Office365_Feed_Test
starttaskid: "0"
tasks:
  "0":
    id: "0"
    taskid: 1ce6cfef-55ee-4279-880b-7f29ae5a8d75
    type: start
    task:
      id: 1ce6cfef-55ee-4279-880b-7f29ae5a8d75
      version: -1
      name: ""
      iscommand: false
      brand: ""
    nexttasks:
      '#none#':
      - "4"
    separatecontext: false
    view: |-
      {
        "position": {
          "x": 50,
          "y": 50
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
    skipunavailable: false
  "1":
    id: "1"
    taskid: 19b89a01-0070-40e5-8163-6bd761da2672
    type: regular
    task:
      id: 19b89a01-0070-40e5-8163-6bd761da2672
      version: -1
      name: Get Indicators - Ofiice365
      script: '|||office365-get-indicators'
      type: regular
      iscommand: true
      brand: ""
    nexttasks:
      '#none#':
      - "2"
    scriptarguments:
      extend-context:
        simple: Indicator.[0]
      indicator_type:
        simple: ips
      limit:
        simple: "10"
    separatecontext: false
    view: |-
      {
        "position": {
          "x": 50,
          "y": 370
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
    skipunavailable: false
  "2":
    id: "2"
    taskid: 8a4e3ec3-44cc-464c-84c9-6a0759b0641e
    type: condition
    task:
      id: 8a4e3ec3-44cc-464c-84c9-6a0759b0641e
      version: -1
      name: Assert Output
      description: Asserts output.
      type: condition
      iscommand: false
      brand: ""
    nexttasks:
      "yes":
      - "3"
    separatecontext: false
    conditions:
    - label: "yes"
      condition:
      - - operator: isNotEmpty
          left:
            value:
              complex:
                root: Indicator
                accessor: type
            iscontext: true
      - - operator: isNotEmpty
          left:
            value:
              simple: Indicator.value
            iscontext: true
    view: |-
      {
        "position": {
          "x": 50,
          "y": 545
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
    skipunavailable: false
  "3":
    id: "3"
    taskid: b02bb7f3-68bb-452f-850f-cbbaeb7fca2a
    type: title
    task:
      id: b02bb7f3-68bb-452f-850f-cbbaeb7fca2a
      version: -1
      name: Done
      description: Done
      type: title
      iscommand: false
      brand: ""
    separatecontext: false
    view: |-
      {
        "position": {
          "x": 50,
          "y": 720
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
    skipunavailable: false
  "4":
    id: "4"
    taskid: 23ee64fd-251d-43d4-870b-d72b8f7bc761
    type: regular
    task:
      id: 23ee64fd-251d-43d4-870b-d72b8f7bc761
      version: -1
      name: Delete Context
      description: Delete field from context.
      scriptName: DeleteContext
      type: regular
      iscommand: false
      brand: ""
    nexttasks:
      '#none#':
      - "1"
    scriptarguments:
      all:
        simple: "yes"
      index: {}
      key: {}
      keysToKeep: {}
      subplaybook: {}
    separatecontext: false
    view: |-
      {
        "position": {
          "x": 50,
          "y": 195
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
    skipunavailable: false
view: |-
  {
    "linkLabelsPosition": {},
    "paper": {
      "dimensions": {
        "height": 735,
        "width": 380,
        "x": 50,
        "y": 50
      }
    }
  }
inputs: []
outputs: []
